name: super_responsive
description: Utils and widgets to make your flutter apps and websites fully responsive.

version: 0.1.2+1

repository: https://github.com/namzug16/super-responsive

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^2.4.0

flutter:

  uses-material-design: true

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: